### ISSUE TITLE
[1pt] Setup kanban board - final group capstone

### ISSUE THREAD

**Issue by Salimer** [Salimer/Final-Capstone-Back-End#16]
Group members:

Facilitator: @Salimer 
Timekeeper: @tamoorsaeed22 
Code checker: @isume295 
Task-assigner: @MarcoDiaz2000 

[Link to the back-end repo:](https://github.com/Salimer/Final-Capstone-Back-End)
[Link to the front-end repo:](https://github.com/Salimer/Final-Capstone-Front-End)
Link to the project: [here](https://github.com/Salimer/Final-Capstone-Back-End/projects/1)
Screenshot of the project board:

![final2](https://github.com/Salimer/Final-Capstone-Back-End/assets/125866339/8a11c76f-a047-43ac-a45a-6bcf02e168be)

**Comment by Meltrust** [comment]
Hi @Salimer

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the project requirements:

![image](https://github.com/Salimer/Final-Capstone-Back-End/assets/57421823/cdc17b5a-c770-49c6-81cb-7d02808c4ede)

This card does not have any points:

![image](https://github.com/Salimer/Final-Capstone-Back-End/assets/57421823/66bfa032-6061-4c35-bd49-bad6f859a77f)

Kindly add some points to this card, in order to meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @Salimer,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards now have pointings✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarcoDiaz2000** [comment]
Thanks
